# Generated by Django 4.0.6 on 2022-09-07 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itbridge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=45, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='itbridge.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
