# Generated by Django 4.0.6 on 2022-08-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itbridge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='type',
            field=models.CharField(choices=[('Festival', 'Festival'), ('Sick', 'Sick'), ('Marriage', 'Marriage'), ('Mourning', 'Mourning')], max_length=100),
        ),
    ]
